docs/AboutUs.adoc
Updated AboutUs page and added profile image placeholder files.
=> Updated AboutUs page

README.adoc
Changed the title in README.adoc
=> Changed the title in README.adoc

docs/team/josephambe.adoc
Create and update project portfolio named 'josephambe.adoc'
=> Update Project Portfolio

src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/test/java/guitests/guihandles/MainWindowHandle.java, src/test/java/systemtests/AddressBookSystemTest.java, src/test/java/systemtests/HelpCommandSystemTest.java
- Three-column layout for new GUI (add two person display columns and remove browserPanel).
- Data is unchanged - still persons instead of modules. 
- Todo: Display mock CAP and provide API to @jeremiah-ang. Modules to be provided by @josephambe. 
Fulfills #49.
=> Gui layout

src/main/java/seedu/address/logic/commands/AddModuleCommand.java, src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/TranscriptParser.java, src/main/java/seedu/address/model/module/Module.java, src/main/java/seedu/address/model/util/ModuleBuilder.java, src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java, src/test/java/seedu/address/logic/parser/TranscriptParserTest.java, src/test/java/seedu/address/testutil/ModuleUtil.java, src/test/java/seedu/address/testutil/TypicalModules.java
Closes #57
1. main/.../logic/parser/AddModuleCommandParser.java - For parsing args for `AddModuleCommand`
2. main/.../logic/parser/TranscriptParser.java - For parsing Transcript
3. test/.../logic/parser/AddModuleCommandParserTest.java - For testing `AddModuleCommandPaser`
4. test/.../logic/parser/TranscriptParser.java - For testing `TranscriptParser`
1. main/.../logic/commands/AddModuleCommand.java - Changed logic in comparing `equals(Object other)`
2. main/.../logic/parser/ParserUtil.java - Added parsers for module components and tokenizer
3. main/.../model/module/Module.java - Changed logic in comparing `equals(Object other)`
4. main/.../model/util/ModuleBuilder.java - Added `noGrade()` to accept modules with no grades
5. test/.../testutil/TypicalModules.java - Reorganise the code
=> Added Parser for Module and Transcript

src/main/java/seedu/address/model/Transcript.java, src/main/java/seedu/address/model/capgoal/CapGoal.java, src/main/java/seedu/address/model/module/Grade.java, src/main/java/seedu/address/model/module/Module.java, src/main/java/seedu/address/model/module/UniqueModuleList.java, src/test/java/seedu/address/model/TranscriptTest.java, src/test/java/seedu/address/model/module/GradeTest.java
1. Adding new Modules
2. Deleting Modules
3. Updating Modules
4. Changes made to capGoal
Blocked by #62 
Closes #36
=> Calculate Target Grade triggers

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/RedoModuleCommand.java, src/main/java/seedu/address/logic/commands/UndoModuleCommand.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/RedoModuleCommandTest.java, src/test/java/seedu/address/logic/commands/UndoModuleCommandTest.java
Add UndoModuleCommand
Add RedoModuleCommand
Update UserGuide
=> Undo/Redo Command

src/test/java/seedu/address/TestApp.java, src/test/java/systemtests/AddressBookSystemTest.java, src/test/java/systemtests/ModelHelper.java
Rename getStorageSaveLocation() to getAddressStorageSaveLocation()
Rename getModel() to getAddressBookModel()
Add methods in TestApp to produce defensive copies of Transcript
Add helper methods in ModelHelper
=> System test setup

README.adoc
Acknowledge SE-EDU as per feedback from feedbackbot
Fixes #94
=> Acknowledge SE-EDU3/4 in README.adoc

src/main/java/seedu/address/model/module/Code.java, src/main/java/seedu/address/model/module/Grade.java
Module code and grade value set to uppercase.
Fixes #92
=> Module code and grade value set to uppercase

src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/Transcript.java, src/main/java/seedu/address/model/capgoal/CapGoal.java, src/test/java/seedu/address/model/TranscriptTest.java
=> refractor CapGoal change names and signatures

docs/DeveloperGuide.adoc
=> Update Use case to follow MSS and Extensions

docs/UserGuide.adoc
Fix documentation to explain `goal` command correctly
=> Fix cap goal command doc

src/main/java/seedu/address/ui/MainWindow.java
Updated the UI to take the correct ObservableList of modules
=> Display correct modules for the two panels

src/main/java/seedu/address/model/Transcript.java, src/main/java/seedu/address/model/capgoal/CapGoal.java, src/main/java/seedu/address/model/module/Grade.java, src/main/java/seedu/address/model/module/Module.java, src/main/java/seedu/address/storage/JsonTranscriptDeserializer.java, src/main/java/seedu/address/ui/CapPanel.java, src/test/data/JsonTranscriptStorageTest/ExtraValuesTranscript.json, src/test/data/JsonTranscriptStorageTest/TypicalTranscript.json, src/test/java/seedu/address/model/module/ModuleTest.java
=> target grades not updating

src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
Fix predicate logic in delete command. Fixes #140
=> Fix delete command logic

src/main/java/seedu/address/logic/commands/EditModuleCommand.java, src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
Fix bug for edit module command:
- Added error message for when multiple module entries with same code exist but year and semester not supplied.
- Fix bug which prevents module with multiple entries to not edit
Fixes #141
=> Fix bug for edit module command

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/EditModuleCommand.java, src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/module/Grade.java, src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java, src/test/java/seedu/address/logic/parser/EditModuleCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/testutil/TypicalModules.java
- Fix parsing bugs
- Refactored `EditModuleCommand`
- Refactored `EditModuleCommandParser`
- Added javadocs for `EditModuleCommand`
- Added javadocs for `EditModuleCommandParser`
- Added `EditModuleCommandParserTest`
- Edited `ParserUtil` to fix `EditModuleCommand`
- Refactored `ParserUtil`
- Added more test in `ParserUtilTest` to cover changes made to fix `EditModuleCommand`
- Refactored `ParserUtil`
Fixes #149 
Fixes #147 
Fixes #159 
Fixes #171
Fixes #179
=> Fix parsing bugs, refactor code, added more unit test

src/main/java/seedu/address/logic/parser/GoalCommandParser.java, src/test/java/seedu/address/logic/parser/GoalCommandParserTest.java
=> Meaningful error message when goal is out of range

src/main/java/seedu/address/model/Transcript.java
=> Calls modulesUpdated on removeModule

docs/UserGuide.adoc
Add `c_` infront of `adjust` into `c_adjust`
fixes #152
=> Update Adjust Command in User Guide

src/test/java/seedu/address/logic/parser/TranscriptParserTest.java, src/test/java/seedu/address/testutil/ModuleUtil.java
Currently, coverall reports that test coverage for `TranscriptParser` is low.
Write more test for `TranscriptParser`.
- Add add module command test
- Add edit module command test
- Add more unit test in `TranscriptParserTest`
- Add helper methods in `ModuleUtil`
Closes #183
=> Write more test for TranscriptParser

src/main/java/seedu/address/logic/commands/AdjustCommand.java, src/main/java/seedu/address/model/module/Module.java, src/main/java/seedu/address/model/util/ModuleBuilder.java, src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java, src/test/java/seedu/address/logic/commands/AdjustCommandTest.java, src/test/java/seedu/address/testutil/TypicalModules.java
=> Prevent Adjust Command from updating Completed Module

docs/UserGuide.adoc
=> Updated UserGuide.adoc to reflect the updated edit command

docs/team/jeremiah-ang.adoc
=> Update jeremiah-ang's PPP

src/main/java/seedu/address/model/Transcript.java, src/main/java/seedu/address/model/exceptions/CapGoalIsImpossibleException.java, src/main/java/seedu/address/model/exceptions/NoTargetableModulesException.java, src/main/java/seedu/address/model/module/Grade.java, src/test/java/seedu/address/model/TranscriptTest.java
Logged Target Grade calculation and CAP calculation procedures.
=> Add logs to CAP and Target Grade Calculation

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, docs/team/jeremiah-ang.adoc, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/CapPanel.java, src/test/java/seedu/address/model/TranscriptTest.java
* Bug Fix
* Adjusting grade was not triggering achievability of CAP Goal
* Documentation
* Add some manual testing guide for CAP Calculation/Target Grade Calculation/Adjusting Grade
* Update PPP
* Test
* Add one more test for Target Grade calculation
Closes #103 
Closes #204
=> Add more tests for CAP calculation and Documentation Update

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AdjustCommand.java, src/main/java/seedu/address/logic/commands/GoalCommand.java, src/main/java/seedu/address/logic/parser/AdjustCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/TranscriptParser.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/parser/AdjustCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditModuleCommandParserTest.java, src/test/java/seedu/address/logic/parser/TranscriptParserTest.java, src/test/java/seedu/address/testutil/ModuleUtil.java, src/test/java/seedu/address/ui/CommandBoxTest.java
=> Remove legacy command & add more tests

docs/UserGuide.adoc
=> Update user guide documentation to reflect changes in add command and other commands

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AdjustCommand.java, src/main/java/seedu/address/logic/commands/CommandUtil.java, src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java, src/main/java/seedu/address/logic/commands/EditModuleCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/Transcript.java, src/main/java/seedu/address/model/VersionedTranscript.java, src/main/java/seedu/address/model/module/UniqueModuleList.java, src/main/java/seedu/address/model/module/exceptions/MultipleModuleEntryFoundException.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java, src/test/java/seedu/address/model/module/UniqueModuleListTest.java
=> Added getOnlyOneModule

src/main/resources/view/ModuleListPanel2.fxml
Updated title to be more correct
=> Changed uncomplete to incomplete title UI

docs/DeveloperGuide.adoc, docs/UserGuide.adoc
Title, and also some minor change to User guide.
=> Update Use Case documentation
